header_background:
  default: #f9e9d7
  description:
    en: "Choose."
whisper_background:
  default: #F7941D
  description:
    en: "Choose."
composing_whisper_background:
  default: #f7edea
  description:
    en: "Choose."
moderator_color:
  default: #888800
  description:
    en: "Choose."
moderator_background:
  default: #ffffea
  description:
    en: "Choose."
